path_classifiers:
  library:
  - third_party/stb
  - third_party/termbox2
extraction:
  cpp:
    prepare:
      packages:
        - libcurl4-openssl-dev
        - liblmdb-dev
    # LGTM's build server's cJSON is over a year old...
    after_prepare:
      - git clone --depth=1 https://github.com/DaveGamble/cJSON ./third_party/cjson
      - export C_INCLUDE_PATH=$PWD/third_party
      - echo "#define curl_multi_poll(...) 0" >> libmatrix_src/matrix-priv.h
      - echo "#define curl_multi_wakeup(...) 0" >> libmatrix_src/matrix-priv.h
      - sed -i -e 's|-lcjson||' -e 's|OBJ = |&third_party/cjson/cJSON.o |' Makefile
